// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cheeseria.Server.DataRepositories;

#nullable disable

namespace cheeseria.Server.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheeseApp.Server.CheeseDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PricePerKilo")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Cheeses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Colour = "Light Yellow",
                            CreatedDate = new DateTime(2024, 6, 1, 20, 35, 21, 207, DateTimeKind.Local).AddTicks(2371),
                            ModifiedDate = new DateTime(2024, 6, 1, 20, 35, 21, 207, DateTimeKind.Local).AddTicks(2381),
                            Name = "Cheddar",
                            PricePerKilo = 7f
                        },
                        new
                        {
                            Id = 2,
                            Colour = "White",
                            CreatedDate = new DateTime(2024, 6, 1, 20, 35, 21, 207, DateTimeKind.Local).AddTicks(2382),
                            ModifiedDate = new DateTime(2024, 6, 1, 20, 35, 21, 207, DateTimeKind.Local).AddTicks(2383),
                            Name = "Feta",
                            PricePerKilo = 50f
                        },
                        new
                        {
                            Id = 3,
                            Colour = "White with Blue Pigment",
                            CreatedDate = new DateTime(2024, 6, 1, 20, 35, 21, 207, DateTimeKind.Local).AddTicks(2384),
                            ModifiedDate = new DateTime(2024, 6, 1, 20, 35, 21, 207, DateTimeKind.Local).AddTicks(2384),
                            Name = "Gorgonzola",
                            PricePerKilo = 21f
                        },
                        new
                        {
                            Id = 4,
                            Colour = "Light Yellow",
                            CreatedDate = new DateTime(2024, 6, 1, 20, 35, 21, 207, DateTimeKind.Local).AddTicks(2385),
                            ModifiedDate = new DateTime(2024, 6, 1, 20, 35, 21, 207, DateTimeKind.Local).AddTicks(2385),
                            Name = "Gouda",
                            PricePerKilo = 3f
                        },
                        new
                        {
                            Id = 5,
                            Colour = "White",
                            CreatedDate = new DateTime(2024, 6, 1, 20, 35, 21, 207, DateTimeKind.Local).AddTicks(2386),
                            ModifiedDate = new DateTime(2024, 6, 1, 20, 35, 21, 207, DateTimeKind.Local).AddTicks(2387),
                            Name = "Aarenwasser",
                            PricePerKilo = 8f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
